before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq txt2tags valgrind
  - sudo pip install cpp-coveralls
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=valgrind
  - TEST_SUITE=clang
script:
  - ./tester . $TEST_SUITE
