before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq txt2tags valgrind
env:
  - ACTION=coverage
  - ACTION=valgrind
  - ACTION=clang
script:
  - ./tester $ACTION
after_success:
  - if [ "$ACTION" = coverage ]; then bash <(curl -s https://codecov.io/bash); fi

