---
language: generic
env:
  - DIST=stretch ARCH=i386
  - DIST=stretch ARCH=amd64
install: docker pull lpenz/debian-${DIST}-${ARCH}
script:
  - docker run -d --name debian -v "$PWD/..:$PWD/.." lpenz/debian-${DIST}-${ARCH} sleep 9999999999
  - docker exec -t debian /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends devscripts equivs git-buildpackage"
  - docker exec -t debian /bin/bash -c "mk-build-deps -i -r --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' $PWD/debian/control"
  - docker exec -t debian /bin/bash -c "cd $PWD && gbp buildpackage --git-ignore-branch -us -uc"
  - docker rm -f debian
  - sudo chown -R "$USER:$USER" ../
  - ls -l ..
deploy:
  provider: packagecloud
  repository: lpenz
  username: lpenz
  token:
    secure: baRx86l7pzXXNDiWQhflqXGXkU4T52Pyc1nIglsPyOA4mxNbIxcO087WQRkXAYSEoj/T2Al+BmdiavtmK4Esl3RJko/mihHGFmqXDYNQwrzo9+UZQ3CvhihelFDvUMGQxxYY51F93pmWdhfUbcPfNq1VqOatnuW7ZAPpXSZzqwo=
  dist: debian/stretch
  local-dir: '..'
  package_glob: '*.deb'
  on:
    branch: debian-debian
    tags: true
