#!/bin/bash

SUITE=$1
EXTRA="-D Experimental"

set -x -e

mkdir $SUITE
cd $SUITE

if [ "$SUITE" = "clang" ]; then
	export CC=clang
elif [ "$SUITE" = "coverage" ]; then
	export CFLAGS=--coverage
	export CXXFLAGS=--coverage
elif [ "$SUITE" = "valgrind" ]; then
	EXTRA="-D ExperimentalMemCheck"
fi

cmake ..
make
ctest $EXTRA

if [ "$SUITE" = "valgrind" ]; then
	ctest -D ExperimentalSubmit
fi

