#!/bin/bash

SOURCE=$1
SUITE=$2
EXTRA="-D Experimental"

set -x -e

if [ "$SUITE" = "clang" ]; then
	export CC=clang
elif [ "$SUITE" = "coverage" ]; then
	export CFLAGS=--coverage
	export CXXFLAGS=--coverage
elif [ "$SUITE" = "valgrind" ]; then
	EXTRA="-D ExperimentalMemCheck"
fi

cmake "$SOURCE"
make VERBOSE=1
ctest $EXTRA

if [ "$SUITE" = "valgrind" ]; then
	ctest -D ExperimentalSubmit
fi

if [ "$SUITE" = "coverage" ]; then
	coveralls -E '.*CMake.*'
fi

