#!/bin/bash

SUITE=$1
SOURCE="$(cd "$(dirname "$0")"; pwd)"
EXTRA="-D Experimental"

set -x -e

mkdir -p "$SUITE"
cd "$SUITE"

if [ "$SUITE" = "clang" ]; then
	export CC=clang
elif [ "$SUITE" = "coverage" ]; then
	export CFLAGS=--coverage
	export CXXFLAGS=--coverage
elif [ "$SUITE" = "valgrind" ]; then
	EXTRA="-D ExperimentalMemCheck"
fi

cmake "$SOURCE"
make VERBOSE=1
ctest "$EXTRA"

if [ "$SUITE" = "valgrind" ]; then
	ctest -D ExperimentalSubmit
fi

